"""add unique constraint to policy title and agency.

Revision ID: 0bf014844282
Revises: a97adcb7685e
Create Date: 2026-04-06 19:39:41.352812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bf014844282'
down_revision: Union[str, Sequence[str], None] = 'a97adcb7685e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_policy_title_agency', 'policies', ['title', 'agency_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_policy_title_agency', 'policies', type_='unique')
    # ### end Alembic commands ###
