"""add_admin_domain_models_and_audit_logs

Revision ID: 17124055eb37
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 10:58:29.675250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17124055eb37'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('biz_picks', 'content_html',
               existing_type=sa.TEXT(),
               comment='HTML 본문 (관리자 API에서 그대로 저장·조회)',
               existing_comment='마크다운 본문',
               existing_nullable=False)
    op.alter_column('user_tokens', 'token',
               existing_type=sa.TEXT(),
               comment='opaque Refresh Token 원본값 저장',
               existing_comment='opaque Refresh Token 값 (SHA-256 다이제스트 저장)',
               existing_nullable=False)
    op.alter_column('user_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               comment='로그아웃·탈퇴로 무효화 여부',
               existing_comment='로그아웃 등으로 무효화 여부',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'military_service',
               existing_type=sa.VARCHAR(length=30),
               comment='군필 여부 (COMPLETED/EXEMPTED/IN_PROGRESS/NA)',
               existing_comment='군필 여부 (COMPLETED / EXEMPTED / IN_PROGRESS / NA)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'military_service',
               existing_type=sa.VARCHAR(length=30),
               comment='군필 여부 (COMPLETED / EXEMPTED / IN_PROGRESS / NA)',
               existing_comment='군필 여부 (COMPLETED/EXEMPTED/IN_PROGRESS/NA)',
               existing_nullable=True)
    op.alter_column('user_tokens', 'is_revoked',
               existing_type=sa.BOOLEAN(),
               comment='로그아웃 등으로 무효화 여부',
               existing_comment='로그아웃·탈퇴로 무효화 여부',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_tokens', 'token',
               existing_type=sa.TEXT(),
               comment='opaque Refresh Token 값 (SHA-256 다이제스트 저장)',
               existing_comment='opaque Refresh Token 원본값 저장',
               existing_nullable=False)
    op.alter_column('biz_picks', 'content_html',
               existing_type=sa.TEXT(),
               comment='마크다운 본문',
               existing_comment='HTML 본문 (관리자 API에서 그대로 저장·조회)',
               existing_nullable=False)
    # ### end Alembic commands ###
