"""Add notification setting columns to user table

Revision ID: 1db6b0205160
Revises: 0bf014844282
Create Date: 2026-04-07 15:53:58.225241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db6b0205160'
down_revision: Union[str, Sequence[str], None] = '0bf014844282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='전체 푸시 알림 활성화 여부 (Master Switch)'))
    op.add_column('users', sa.Column('marketing_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='마케팅/광고성 정보 수신 동의 여부'))
    op.add_column('users', sa.Column('policy_update_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='서비스 이용약관 및 정책 변경 알림 수신 여부'))
    op.add_column('users', sa.Column('chat_answer_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='AI 채팅 답변 완료 알림 수신 여부'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_answer_enabled')
    op.drop_column('users', 'policy_update_enabled')
    op.drop_column('users', 'marketing_enabled')
    op.drop_column('users', 'push_enabled')
    # ### end Alembic commands ###
