"""add_businesses_policies_chat_rooms

Revision ID: 42c9a8c454fc
Revises: 7e8991976b65
Create Date: 2026-03-30 18:54:52.168913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42c9a8c454fc'
down_revision: Union[str, Sequence[str], None] = '7e8991976b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False, comment='정책(공고) 고유 식별자'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='공고 제목'),
    sa.Column('agency_name', sa.String(length=100), nullable=False, comment='공고 기관명'),
    sa.Column('support_type', sa.String(length=50), nullable=True, comment='지원 유형 (융자·출연금·보조금 등)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='리스트용 3줄 요약 (AI 생성)'),
    sa.Column('ai_full_explanation', sa.Text(), nullable=True, comment='상세용 쉬운 풀이 (AI 생성)'),
    sa.Column('content_raw', sa.Text(), nullable=False, comment='공고 원문 전체 (RAG·분석용)'),
    sa.Column('max_support', sa.BigInteger(), nullable=True, comment='최대 지원 금액'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='접수 시작일'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='접수 종료일'),
    sa.Column('status', sa.Enum('PREPARING', 'RECRUITING', 'CLOSED', 'END_OF_BUDGET', name='policystatus'), nullable=False, comment='공고 상태 (예정·접수중·마감·예산소진)'),
    sa.Column('apply_url', sa.Text(), nullable=True, comment='원문 신청 페이지 URL'),
    sa.Column('target_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='사업장 대비 매칭 필터 규칙 (JSON)'),
    sa.Column('bonus_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='가산점 계산 규칙 (JSON)'),
    sa.Column('scrap_source_url', sa.Text(), nullable=True, comment='크롤링·수집 원본 페이지 주소'),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='상세 조회 누적 건수'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False, comment='사업장 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='이 사업장을 소유한 사용자 ID (users.id)'),
    sa.Column('biz_name', sa.String(length=100), nullable=False, comment='상호명'),
    sa.Column('representative_name', sa.String(length=50), nullable=True, comment='대표자명'),
    sa.Column('biz_no', sa.String(length=12), nullable=True, comment='사업자등록번호'),
    sa.Column('ksic_code', sa.String(length=20), nullable=True, comment='표준산업분류코드'),
    sa.Column('sector_code', sa.String(length=20), nullable=True, comment='세부 업종 코드'),
    sa.Column('region_sido', sa.String(length=50), nullable=True, comment='시·도 (표시·매칭용)'),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True, comment='시·군·구 (표시·매칭용)'),
    sa.Column('region_code', sa.String(length=10), nullable=True, comment='법정동 코드 (시스템 지역 필터용)'),
    sa.Column('establishment_date', sa.Date(), nullable=True, comment='설립 일자 (업력 등 자격 판단)'),
    sa.Column('has_patent', sa.Boolean(), nullable=False, comment='특허 보유 여부'),
    sa.Column('is_female_ent', sa.Boolean(), nullable=False, comment='여성 기업 여부'),
    sa.Column('is_ventured', sa.Boolean(), nullable=False, comment='벤처 기업 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='업장 활성 여부 (폐업·삭제 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='사업장 정보 최초 등록 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False, comment='대화방(상담 세션) 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='상담을 시작한 사용자 ID (users.id)'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='상담 시 선택된 사업장 ID (businesses.id, 데이터 격리)'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='대화방 제목 (AI 요약 등)'),
    sa.Column('user_feedback', sa.Boolean(), nullable=True, comment='사용자 만족도 (좋아요·싫어요 등)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상담 진행 상태 (진행·종료 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='대화방 생성 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_rooms')
    op.drop_table('businesses')
    op.drop_table('policies')
    op.execute(text("DROP TYPE IF EXISTS policystatus"))
    # ### end Alembic commands ###
