"""auto_add_origin_id_to_policy

Revision ID: e07de3ca211b
Revises: f273a5a15134
Create Date: 2026-04-08 18:36:46.559560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07de3ca211b'
down_revision: Union[str, Sequence[str], None] = 'f273a5a15134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('origin_id', sa.String(length=100), nullable=True, comment='외부 원천 API의 고유 공고 식별자 (예: 기업마당 pblancId)'))
    op.create_unique_constraint(None, 'policies', ['origin_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'policies', type_='unique')
    op.drop_column('policies', 'origin_id')
    # ### end Alembic commands ###
