"""add_profile_score_to_business

Revision ID: 984ee159a4ca
Revises: da6e1e2712e6
Create Date: 2026-03-31 19:25:25.935508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "984ee159a4ca"
down_revision: Union[str, Sequence[str], None] = "da6e1e2712e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesses",
        sa.Column(
            "profile_score",
            sa.Integer(),
            server_default=sa.text(
                "0"
            ),  # 👈 이 부분이 핵심입니다! DB 차원에서 0을 기본값으로 박아줘요.
            nullable=False,
            comment="사업장 정보 완성도 (0~100)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesses", "profile_score")
    # ### end Alembic commands ###
