"""서비스기능확장에 따른 DB구조 변경

Revision ID: a97adcb7685e
Revises: a4b5c6d7e8f9
Create Date: 2026-04-06 13:59:34.547543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a97adcb7685e'
down_revision: Union[str, Sequence[str], None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_picks', sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='조회수'))
    op.add_column('biz_picks', sa.Column('like_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='좋아요 수 (인기 콘텐츠 정렬 기준)'))
    op.alter_column('biz_picks', 'id',
               existing_type=sa.UUID(),
               comment='콘텐츠 고유 ID',
               existing_comment='콘텐츠 고유 식별자',
               existing_nullable=False)
    op.alter_column('biz_picks', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='카테고리 (세무·정책자금 등 분류)',
               existing_comment='카테고리 (세무·정책자금 등)',
               existing_nullable=False)
    op.alter_column('biz_picks', 'content_html',
               existing_type=sa.TEXT(),
               comment='HTML 본문 (관리자 도구에서 작성된 원본)',
               existing_comment='HTML 본문 (관리자 API에서 그대로 저장·조회)',
               existing_nullable=False)
    op.alter_column('biz_picks', 'thumbnail_url',
               existing_type=sa.TEXT(),
               comment='썸네일 이미지 주소',
               existing_comment='썸네일 이미지 URL',
               existing_nullable=True)
    op.alter_column('biz_picks', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='공개 여부 (준비 중인 글은 숨김)',
               existing_comment='발행(공개) 여부',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('biz_picks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='발행 시점',
               existing_comment='작성·발행 일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_biz_picks_category'), 'biz_picks', ['category'], unique=False)
    op.alter_column('business_financial_snapshots', 'annual_revenue',
               existing_type=sa.BIGINT(),
               comment='연매출액 (원)',
               existing_comment='연매출액',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'net_income',
               existing_type=sa.BIGINT(),
               comment='당기순이익 (원, 음수 가능)',
               existing_comment='당기순이익',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'total_debt',
               existing_type=sa.BIGINT(),
               comment='총 부채액 (원)',
               existing_comment='총 부채액',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'debt_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='부채 비율 (%) — 자동 계산',
               existing_comment='부채 비율 (%)',
               existing_nullable=True)
    op.alter_column('documents', 'ocr_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='OCR 추출 원본 데이터 (JSON). 비동기 분석 완료 시 update_document_status()로 채워진다. API 명세서 #11 ocr_data 필드에 대응.',
               existing_comment='OCR 추출 원본 데이터 (COMPLETED 상태일 때 채워짐) — API 명세서 #11',
               existing_nullable=True)
    op.add_column('notifications', sa.Column('title', sa.String(length=255), server_default=sa.text("'새로운 알림'"), nullable=False, comment='알림 제목 (사용자에게 노출될 큰 글씨의 요약 내용입니다)'))
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               comment='알림 고유 식별자 (자동 생성되는 우편물 번호입니다)',
               existing_comment='알림 고유 식별자',
               existing_nullable=False)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               comment='수신 사용자 ID (누구에게 보낼지 정하는 수신인 주소입니다)',
               existing_comment='수신 사용자 ID (users.id)',
               existing_nullable=False)
    op.alter_column('notifications', 'business_id',
               existing_type=sa.UUID(),
               comment='연관 사업장 ID (특정 가게와 관련된 알림일 경우에만 기록합니다)',
               existing_comment='연관 사업장 ID (businesses.id, 가게별 필터용)',
               existing_nullable=True)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='알림 유형 (예: POLICY_MATCH, CHAT_ANSWER 등 유형별 아이콘 구분에 사용)',
               existing_comment='알림 유형 (매칭·공지 등)',
               existing_nullable=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='알림 본문 (상세한 안내 문구가 담기는 그릇입니다)',
               existing_comment='알림 본문',
               existing_nullable=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='읽음 여부 (사용자가 확인했는지 체크하는 확인 도장입니다)',
               existing_comment='읽음 여부',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'link_url',
               existing_type=sa.TEXT(),
               comment='이동 URL (클릭 시 앱/웹 내 특정 페이지로 안내하는 지름길입니다)',
               existing_comment='이동 URL',
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_comment='알림 생성 일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('policies', sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI 추천 엔진용 메타데이터 (가중치, 벡터 DB 참조 ID 등 임시 저장소)'))
    op.alter_column('policies', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='공고 제목 (검색 최적화 인덱스 적용)',
               existing_comment='공고 제목',
               existing_nullable=False)
    op.alter_column('policies', 'agency_name',
               existing_type=sa.VARCHAR(length=100),
               comment='공고 기관명 (주관 부처 검색용)',
               existing_comment='공고 기관명',
               existing_nullable=False)
    op.alter_column('policies', 'region',
               existing_type=sa.VARCHAR(length=100),
               comment='지원 대상 지역 (전국/서울 등)',
               existing_comment='지원 대상 지역 (검색·필터용)',
               existing_nullable=True)
    op.alter_column('policies', 'ai_summary',
               existing_type=sa.TEXT(),
               comment='리스트용 3줄 요약 (AI가 읽기 쉽게 가공한 데이터)',
               existing_comment='리스트용 3줄 요약 (AI 생성)',
               existing_nullable=True)
    op.alter_column('policies', 'ai_full_explanation',
               existing_type=sa.TEXT(),
               comment='상세용 쉬운 풀이 (비전공자 사용자를 위한 AI 해설)',
               existing_comment='상세용 쉬운 풀이 (AI 생성)',
               existing_nullable=True)
    op.alter_column('policies', 'content_raw',
               existing_type=sa.TEXT(),
               comment='공고 원문 전체 (RAG 엔진이 학습하고 분석할 실제 원천 데이터)',
               existing_comment='공고 원문 전체 (RAG·분석용)',
               existing_nullable=False)
    op.alter_column('policies', 'max_support',
               existing_type=sa.BIGINT(),
               comment='최대 지원 금액 (원 단위, 통계 및 정렬용)',
               existing_comment='최대 지원 금액',
               existing_nullable=True)
    op.alter_column('policies', 'support_amount_desc',
               existing_type=sa.VARCHAR(length=100),
               comment='지원 금액 표시 문자열 (사용자에게 직접 보여줄 텍스트)',
               existing_comment='지원 금액 표시 문자열 (예: 최대 400만원)',
               existing_nullable=True)
    op.alter_column('policies', 'required_documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='신청 필수 서류 목록 (JSON 배열: AI가 원문에서 추출하여 저장)',
               existing_comment='신청 필수 서류 목록 (문자열 배열 JSON)',
               existing_nullable=True)
    op.alter_column('policies', 'end_date',
               existing_type=sa.DATE(),
               comment='접수 종료일 (하위 호환성 유지용)',
               existing_comment='접수 종료일',
               existing_nullable=True)
    op.alter_column('policies', 'closed_at',
               existing_type=sa.DATE(),
               comment='최종 마감일. 상시접수는 9999-12-31 저장 (정렬 및 필터링 핵심 필드)',
               existing_comment='접수 마감일. 상시접수는 9999-12-31 저장',
               existing_nullable=False,
               existing_server_default=sa.text("'9999-12-31'::date"))
    op.alter_column('policies', 'status',
               existing_type=postgresql.ENUM('PREPARING', 'RECRUITING', 'CLOSED', 'END_OF_BUDGET', name='policystatus'),
               type_=sa.Enum('PREPARING', 'RECRUITING', 'CLOSED', 'END_OF_BUDGET', name='policystatus', native_enum=False),
               comment='공고 상태 (예예정·접수중·마감 등)',
               existing_comment='공고 상태 (예정·접수중·마감·예산소진)',
               existing_nullable=False)
    op.alter_column('policies', 'apply_url',
               existing_type=sa.TEXT(),
               comment='원문 신청 페이지 URL (외부 링크)',
               existing_comment='원문 신청 페이지 URL',
               existing_nullable=True)
    op.alter_column('policies', 'target_logic',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='사업장 매칭 필터 규칙 (AI가 판단할 기준점)',
               existing_comment='사업장 대비 매칭 필터 규칙 (JSON)',
               existing_nullable=True)
    op.alter_column('policies', 'bonus_logic',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='가산점 계산 규칙 (우대 사항 점수화)',
               existing_comment='가산점 계산 규칙 (JSON)',
               existing_nullable=True)
    op.alter_column('policies', 'view_count',
               existing_type=sa.INTEGER(),
               comment='상세 조회 누적 건수 (인기 정책 산출 근거)',
               existing_comment='상세 조회 누적 건수',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='[Soft Delete] 실제 삭제 대신 숨김 처리하여 데이터 무결성 유지',
               existing_comment='[Soft Delete] 활성 여부 — False이면 서비스에서 노출 안 됨',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='데이터 생성 시점',
               existing_comment='등록 일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_policies_agency_name'), 'policies', ['agency_name'], unique=False)
    op.create_index(op.f('ix_policies_category'), 'policies', ['category'], unique=False)
    op.create_index(op.f('ix_policies_closed_at'), 'policies', ['closed_at'], unique=False)
    op.create_index(op.f('ix_policies_region'), 'policies', ['region'], unique=False)
    op.create_index(op.f('ix_policies_title'), 'policies', ['title'], unique=False)
    op.drop_column('policies', 'scrap_source_url')
    op.alter_column('policy_bookmarks', 'id',
               existing_type=sa.UUID(),
               comment='북마크 식별자',
               existing_comment='북마크 고유 식별자',
               existing_nullable=False)
    op.alter_column('policy_bookmarks', 'business_id',
               existing_type=sa.UUID(),
               comment='북마크 주인 (어느 사업장인가?)',
               existing_comment='북마크한 사업장 ID (businesses.id)',
               existing_nullable=False)
    op.alter_column('policy_bookmarks', 'policy_id',
               existing_type=sa.UUID(),
               comment='북마크 대상 (어떤 정책인가?)',
               existing_comment='북마크 대상 정책 ID (policies.id)',
               existing_nullable=False)
    op.alter_column('policy_bookmarks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='북마크 클릭 시점',
               existing_comment='북마크 등록 일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_policy_bookmarks_business_id'), table_name='policy_bookmarks')
    op.drop_index(op.f('ix_policy_bookmarks_policy_id'), table_name='policy_bookmarks')
    op.create_index('ix_policy_bookmark_business_id', 'policy_bookmarks', ['business_id'], unique=False)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='탈퇴 시각(UTC). 5년 후 물리 삭제를 위한 타임스탬프 기록',
               existing_comment='탈퇴 시각(UTC). 도메인 규칙 1.2: 최대 5년 보관 후 물리 삭제 판단 기준',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='탈퇴 시각(UTC). 도메인 규칙 1.2: 최대 5년 보관 후 물리 삭제 판단 기준',
               existing_comment='탈퇴 시각(UTC). 5년 후 물리 삭제를 위한 타임스탬프 기록',
               existing_nullable=True)
    op.drop_index('ix_policy_bookmark_business_id', table_name='policy_bookmarks')
    op.create_index(op.f('ix_policy_bookmarks_policy_id'), 'policy_bookmarks', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_bookmarks_business_id'), 'policy_bookmarks', ['business_id'], unique=False)
    op.alter_column('policy_bookmarks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='북마크 등록 일시',
               existing_comment='북마크 클릭 시점',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('policy_bookmarks', 'policy_id',
               existing_type=sa.UUID(),
               comment='북마크 대상 정책 ID (policies.id)',
               existing_comment='북마크 대상 (어떤 정책인가?)',
               existing_nullable=False)
    op.alter_column('policy_bookmarks', 'business_id',
               existing_type=sa.UUID(),
               comment='북마크한 사업장 ID (businesses.id)',
               existing_comment='북마크 주인 (어느 사업장인가?)',
               existing_nullable=False)
    op.alter_column('policy_bookmarks', 'id',
               existing_type=sa.UUID(),
               comment='북마크 고유 식별자',
               existing_comment='북마크 식별자',
               existing_nullable=False)
    op.add_column('policies', sa.Column('scrap_source_url', sa.TEXT(), autoincrement=False, nullable=True, comment='크롤링·수집 원본 페이지 주소'))
    op.drop_index(op.f('ix_policies_title'), table_name='policies')
    op.drop_index(op.f('ix_policies_region'), table_name='policies')
    op.drop_index(op.f('ix_policies_closed_at'), table_name='policies')
    op.drop_index(op.f('ix_policies_category'), table_name='policies')
    op.drop_index(op.f('ix_policies_agency_name'), table_name='policies')
    op.alter_column('policies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='등록 일시',
               existing_comment='데이터 생성 시점',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('policies', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='[Soft Delete] 활성 여부 — False이면 서비스에서 노출 안 됨',
               existing_comment='[Soft Delete] 실제 삭제 대신 숨김 처리하여 데이터 무결성 유지',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('policies', 'view_count',
               existing_type=sa.INTEGER(),
               comment='상세 조회 누적 건수',
               existing_comment='상세 조회 누적 건수 (인기 정책 산출 근거)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('policies', 'bonus_logic',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='가산점 계산 규칙 (JSON)',
               existing_comment='가산점 계산 규칙 (우대 사항 점수화)',
               existing_nullable=True)
    op.alter_column('policies', 'target_logic',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='사업장 대비 매칭 필터 규칙 (JSON)',
               existing_comment='사업장 매칭 필터 규칙 (AI가 판단할 기준점)',
               existing_nullable=True)
    op.alter_column('policies', 'apply_url',
               existing_type=sa.TEXT(),
               comment='원문 신청 페이지 URL',
               existing_comment='원문 신청 페이지 URL (외부 링크)',
               existing_nullable=True)
    op.alter_column('policies', 'status',
               existing_type=sa.Enum('PREPARING', 'RECRUITING', 'CLOSED', 'END_OF_BUDGET', name='policystatus', native_enum=False),
               type_=postgresql.ENUM('PREPARING', 'RECRUITING', 'CLOSED', 'END_OF_BUDGET', name='policystatus'),
               comment='공고 상태 (예정·접수중·마감·예산소진)',
               existing_comment='공고 상태 (예예정·접수중·마감 등)',
               existing_nullable=False)
    op.alter_column('policies', 'closed_at',
               existing_type=sa.DATE(),
               comment='접수 마감일. 상시접수는 9999-12-31 저장',
               existing_comment='최종 마감일. 상시접수는 9999-12-31 저장 (정렬 및 필터링 핵심 필드)',
               existing_nullable=False,
               existing_server_default=sa.text("'9999-12-31'::date"))
    op.alter_column('policies', 'end_date',
               existing_type=sa.DATE(),
               comment='접수 종료일',
               existing_comment='접수 종료일 (하위 호환성 유지용)',
               existing_nullable=True)
    op.alter_column('policies', 'required_documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='신청 필수 서류 목록 (문자열 배열 JSON)',
               existing_comment='신청 필수 서류 목록 (JSON 배열: AI가 원문에서 추출하여 저장)',
               existing_nullable=True)
    op.alter_column('policies', 'support_amount_desc',
               existing_type=sa.VARCHAR(length=100),
               comment='지원 금액 표시 문자열 (예: 최대 400만원)',
               existing_comment='지원 금액 표시 문자열 (사용자에게 직접 보여줄 텍스트)',
               existing_nullable=True)
    op.alter_column('policies', 'max_support',
               existing_type=sa.BIGINT(),
               comment='최대 지원 금액',
               existing_comment='최대 지원 금액 (원 단위, 통계 및 정렬용)',
               existing_nullable=True)
    op.alter_column('policies', 'content_raw',
               existing_type=sa.TEXT(),
               comment='공고 원문 전체 (RAG·분석용)',
               existing_comment='공고 원문 전체 (RAG 엔진이 학습하고 분석할 실제 원천 데이터)',
               existing_nullable=False)
    op.alter_column('policies', 'ai_full_explanation',
               existing_type=sa.TEXT(),
               comment='상세용 쉬운 풀이 (AI 생성)',
               existing_comment='상세용 쉬운 풀이 (비전공자 사용자를 위한 AI 해설)',
               existing_nullable=True)
    op.alter_column('policies', 'ai_summary',
               existing_type=sa.TEXT(),
               comment='리스트용 3줄 요약 (AI 생성)',
               existing_comment='리스트용 3줄 요약 (AI가 읽기 쉽게 가공한 데이터)',
               existing_nullable=True)
    op.alter_column('policies', 'region',
               existing_type=sa.VARCHAR(length=100),
               comment='지원 대상 지역 (검색·필터용)',
               existing_comment='지원 대상 지역 (전국/서울 등)',
               existing_nullable=True)
    op.alter_column('policies', 'agency_name',
               existing_type=sa.VARCHAR(length=100),
               comment='공고 기관명',
               existing_comment='공고 기관명 (주관 부처 검색용)',
               existing_nullable=False)
    op.alter_column('policies', 'title',
               existing_type=sa.VARCHAR(length=255),
               comment='공고 제목',
               existing_comment='공고 제목 (검색 최적화 인덱스 적용)',
               existing_nullable=False)
    op.drop_column('policies', 'ai_metadata')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='알림 생성 일시',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('notifications', 'link_url',
               existing_type=sa.TEXT(),
               comment='이동 URL',
               existing_comment='이동 URL (클릭 시 앱/웹 내 특정 페이지로 안내하는 지름길입니다)',
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               comment='읽음 여부',
               existing_comment='읽음 여부 (사용자가 확인했는지 체크하는 확인 도장입니다)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               comment='알림 본문',
               existing_comment='알림 본문 (상세한 안내 문구가 담기는 그릇입니다)',
               existing_nullable=False)
    op.alter_column('notifications', 'type',
               existing_type=sa.VARCHAR(length=20),
               comment='알림 유형 (매칭·공지 등)',
               existing_comment='알림 유형 (예: POLICY_MATCH, CHAT_ANSWER 등 유형별 아이콘 구분에 사용)',
               existing_nullable=False)
    op.alter_column('notifications', 'business_id',
               existing_type=sa.UUID(),
               comment='연관 사업장 ID (businesses.id, 가게별 필터용)',
               existing_comment='연관 사업장 ID (특정 가게와 관련된 알림일 경우에만 기록합니다)',
               existing_nullable=True)
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               comment='수신 사용자 ID (users.id)',
               existing_comment='수신 사용자 ID (누구에게 보낼지 정하는 수신인 주소입니다)',
               existing_nullable=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               comment='알림 고유 식별자',
               existing_comment='알림 고유 식별자 (자동 생성되는 우편물 번호입니다)',
               existing_nullable=False)
    op.drop_column('notifications', 'title')
    op.alter_column('documents', 'ocr_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='OCR 추출 원본 데이터 (COMPLETED 상태일 때 채워짐) — API 명세서 #11',
               existing_comment='OCR 추출 원본 데이터 (JSON). 비동기 분석 완료 시 update_document_status()로 채워진다. API 명세서 #11 ocr_data 필드에 대응.',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'debt_ratio',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='부채 비율 (%)',
               existing_comment='부채 비율 (%) — 자동 계산',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'total_debt',
               existing_type=sa.BIGINT(),
               comment='총 부채액',
               existing_comment='총 부채액 (원)',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'net_income',
               existing_type=sa.BIGINT(),
               comment='당기순이익',
               existing_comment='당기순이익 (원, 음수 가능)',
               existing_nullable=True)
    op.alter_column('business_financial_snapshots', 'annual_revenue',
               existing_type=sa.BIGINT(),
               comment='연매출액',
               existing_comment='연매출액 (원)',
               existing_nullable=True)
    op.drop_index(op.f('ix_biz_picks_category'), table_name='biz_picks')
    op.alter_column('biz_picks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='작성·발행 일시',
               existing_comment='발행 시점',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('biz_picks', 'is_published',
               existing_type=sa.BOOLEAN(),
               comment='발행(공개) 여부',
               existing_comment='공개 여부 (준비 중인 글은 숨김)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('biz_picks', 'thumbnail_url',
               existing_type=sa.TEXT(),
               comment='썸네일 이미지 URL',
               existing_comment='썸네일 이미지 주소',
               existing_nullable=True)
    op.alter_column('biz_picks', 'content_html',
               existing_type=sa.TEXT(),
               comment='HTML 본문 (관리자 API에서 그대로 저장·조회)',
               existing_comment='HTML 본문 (관리자 도구에서 작성된 원본)',
               existing_nullable=False)
    op.alter_column('biz_picks', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='카테고리 (세무·정책자금 등)',
               existing_comment='카테고리 (세무·정책자금 등 분류)',
               existing_nullable=False)
    op.alter_column('biz_picks', 'id',
               existing_type=sa.UUID(),
               comment='콘텐츠 고유 식별자',
               existing_comment='콘텐츠 고유 ID',
               existing_nullable=False)
    op.drop_column('biz_picks', 'like_count')
    op.drop_column('biz_picks', 'view_count')
    # ### end Alembic commands ###
