"""initial_schema_reset

Revision ID: c7143fb55e37
Revises: 
Create Date: 2026-04-24 15:13:15.904549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7143fb55e37'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False, comment='관리자 고유 식별자'),
    sa.Column('login_id', sa.String(length=50), nullable=False, comment='관리자 로그인 ID'),
    sa.Column('password', sa.Text(), nullable=False, comment='비밀번호 해시'),
    sa.Column('role', sa.Enum('MASTER', 'OPERATOR', 'CS', name='adminrole'), nullable=False, comment='권한 등급 (MASTER·OPERATOR·CS)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='계정 활성 여부'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='계정 생성 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('batch_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='배치 실행 로그 고유 식별자'),
    sa.Column('job_name', sa.String(length=100), nullable=False, comment='작업 명칭 (예: POLICY_CRAWLING)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='실행 상태 (SUCCESS·FAILED·RUNNING 등)'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='처리 대상 전체 건수'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='성공 반영 건수'),
    sa.Column('fail_count', sa.Integer(), nullable=False, comment='실패 건수 (api+parse+analysis+db 합산)'),
    sa.Column('api_error_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='API 페이지 요청 자체 실패 건수'),
    sa.Column('parse_error_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='첨부파일 텍스트 추출 실패 건수'),
    sa.Column('analysis_error_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='AI 분석·검증 실패 건수'),
    sa.Column('db_fail_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='DB upsert 실패 건수'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='단계별 에러 요약 및 항목 목록 (JSON)'),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='작업 시작 일시'),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True, comment='작업 종료 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biz_picks',
    sa.Column('id', sa.UUID(), nullable=False, comment='콘텐츠 고유 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='콘텐츠 제목 (리스트 노출용)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='카테고리 (세무·정책자금·노무 등)'),
    sa.Column('content_html', sa.Text(), nullable=False, comment='HTML 본문 (Rich Text 에디터 원본)'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='썸네일 이미지 주소'),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='공개 여부 (False면 임시 저장/비공개)'),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='누적 조회수'),
    sa.Column('like_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='좋아요 수 (인기순 정렬에 활용)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='발행 시점'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biz_picks_category'), 'biz_picks', ['category'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False, comment='정책(공고) 고유 식별자'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='공고 제목 (검색 최적화 인덱스 적용)'),
    sa.Column('agency_name', sa.String(length=100), nullable=False, comment='공고 기관명 (주관 부처 검색용)'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='정책 카테고리 (금융/바우처, R&D 등)'),
    sa.Column('support_type', sa.String(length=50), nullable=True, comment='지원 유형 (융자·출연금·보조금 등)'),
    sa.Column('region', sa.String(length=100), nullable=True, comment='지원 대상 지역 (전국/서울 등)'),
    sa.Column('origin_id', sa.String(length=100), nullable=True, comment='외부 원천 API의 고유 공고 식별자 (예: 기업마당 pblancId)'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='리스트용 3줄 요약 (AI가 읽기 쉽게 가공한 데이터)'),
    sa.Column('ai_full_explanation', sa.Text(), nullable=True, comment='상세용 쉬운 풀이 (비전공자 사용자를 위한 AI 해설)'),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='AI 추천 엔진용 메타데이터 (가중치, 벡터 DB 참조 ID 등 임시 저장소)'),
    sa.Column('content_raw', sa.Text(), nullable=False, comment='공고 원문 전체 (RAG 엔진이 학습하고 분석할 실제 원천 데이터)'),
    sa.Column('max_support', sa.BigInteger(), nullable=True, comment='최대 지원 금액 (원 단위, 통계 및 정렬용)'),
    sa.Column('min_support', sa.BigInteger(), nullable=True, comment='최소 지원 금액 (원)'),
    sa.Column('support_amount_desc', sa.String(length=100), nullable=True, comment='지원 금액 표시 문자열 (사용자에게 직접 보여줄 텍스트)'),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='신청 필수 서류 목록 (JSON 배열: AI가 원문에서 추출하여 저장)'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='접수 시작일'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='접수 종료일 (하위 호환성 유지용)'),
    sa.Column('closed_at', sa.Date(), server_default=sa.text("'9999-12-31'"), nullable=False, comment='최종 마감일. 상시접수는 9999-12-31 저장 (정렬 및 필터링 핵심 필드)'),
    sa.Column('status', sa.Enum('PREPARING', 'RECRUITING', 'CLOSED', 'END_OF_BUDGET', name='policystatus', native_enum=False), nullable=False, comment='공고 상태 (예예정·접수중·마감 등)'),
    sa.Column('apply_url', sa.Text(), nullable=True, comment='원문 신청 페이지 URL (외부 링크)'),
    sa.Column('target_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='사업장 매칭 필터 규칙 (AI가 판단할 기준점)'),
    sa.Column('bonus_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='가산점 계산 규칙 (우대 사항 점수화)'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='content_raw의 SHA-256 해시 (임베딩 변경 감지용)'),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='상세 조회 누적 건수 (인기 정책 산출 근거)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='[Soft Delete] 실제 삭제 대신 숨김 처리하여 데이터 무결성 유지'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='데이터 생성 시점'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_id')
    )
    op.create_index(op.f('ix_policies_agency_name'), 'policies', ['agency_name'], unique=False)
    op.create_index(op.f('ix_policies_category'), 'policies', ['category'], unique=False)
    op.create_index(op.f('ix_policies_closed_at'), 'policies', ['closed_at'], unique=False)
    op.create_index(op.f('ix_policies_content_hash'), 'policies', ['content_hash'], unique=False)
    op.create_index(op.f('ix_policies_region'), 'policies', ['region'], unique=False)
    op.create_index(op.f('ix_policies_title'), 'policies', ['title'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='사용자 고유 식별자'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('social_id', sa.String(length=255), nullable=False),
    sa.Column('social_provider', sa.Enum('KAKAO', 'NAVER', name='socialprovider'), nullable=False),
    sa.Column('profile_image_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True, comment='탈퇴 시각(UTC). 5년 후 물리 삭제를 위한 기록'),
    sa.Column('marketing_agreed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('interest_sectors', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='관심 업종 리스트'),
    sa.Column('military_service', sa.String(length=30), nullable=True, comment='군필 여부 (COMPLETED/EXEMPTED/IN_PROGRESS/NA)'),
    sa.Column('is_non_major', sa.Boolean(), nullable=True, comment='비전공 창업자 여부'),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='기술 스택 리스트'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='전체 푸시 알림 마스터 스위치'),
    sa.Column('marketing_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='마케팅 정보 수신 동의 여부'),
    sa.Column('policy_update_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='약관 및 정책 변경 알림 수신 여부'),
    sa.Column('chat_answer_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='AI 채팅 답변 완료 알림 수신 여부'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='감사 로그 고유 식별자'),
    sa.Column('admin_id', sa.UUID(), nullable=False, comment='작업 수행 관리자 ID (admins.id)'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='작업 유형 (POLICY_UPDATE 등)'),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='대상 엔티티 PK'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='변경 전·후 스냅샷 (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='요청 IP (IPv4/IPv6)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='작업 발생 일시'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False, comment='사업장 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='이 사업장을 소유한 사용자 ID (users.id)'),
    sa.Column('biz_name', sa.String(length=100), nullable=False, comment='상호명'),
    sa.Column('representative_name', sa.String(length=50), nullable=True, comment='대표자명'),
    sa.Column('biz_no', sa.String(length=12), nullable=True, comment='사업자등록번호'),
    sa.Column('ksic_code', sa.String(length=20), nullable=True, comment='표준산업분류코드'),
    sa.Column('sector_code', sa.String(length=20), nullable=True, comment='세부 업종 코드'),
    sa.Column('region_sido', sa.String(length=50), nullable=True, comment='시·도 (표시·매칭용)'),
    sa.Column('region_sigungu', sa.String(length=50), nullable=True, comment='시·군·구 (표시·매칭용)'),
    sa.Column('region_code', sa.String(length=10), nullable=True, comment='법정동 코드 (시스템 지역 필터용)'),
    sa.Column('establishment_date', sa.Date(), nullable=True, comment='설립 일자 (업력 등 자격 판단)'),
    sa.Column('has_patent', sa.Boolean(), nullable=False, comment='특허 보유 여부'),
    sa.Column('is_female_ent', sa.Boolean(), nullable=False, comment='여성 기업 여부'),
    sa.Column('is_ventured', sa.Boolean(), nullable=False, comment='벤처 기업 여부'),
    sa.Column('profile_score', sa.Integer(), nullable=False, comment='사업장 정보 완성도 (0~100)'),
    sa.Column('is_biz_no_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='국세청 API 진위 확인 완료 여부 (True 이면 재호출 불필요)'),
    sa.Column('biz_verified_status', sa.String(length=30), nullable=True, comment='국세청 반환 사업자 상태 (계속사업자 | 휴업자 | 폐업자 등)'),
    sa.Column('tax_type', sa.String(length=50), nullable=True, comment='국세청 반환 과세 유형 (부가가치세 일반과세자 등)'),
    sa.Column('biz_verified_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='국세청 API 마지막 검증 시각 (UTC)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='업장 활성 여부 (폐업·삭제 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='사업장 정보 최초 등록 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='청크 고유 식별자'),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='원본 정책 ID (policies.id 참조)'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='정책 내 청크 순서 (0-based)'),
    sa.Column('chunk_type', sa.String(length=100), nullable=False, comment='섹션 종류 (지원대상/지원내용/신청방법 등 또는 본문_N)'),
    sa.Column('chunk_text', sa.Text(), nullable=False, comment='청크 원문 텍스트'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True, comment='OpenAI text-embedding-3-small 벡터 (1536차원)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='청크 생성 시점'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_policy_chunks_policy_id', 'policy_chunks', ['policy_id'], unique=False)
    op.create_table('user_tokens',
    sa.Column('id', sa.UUID(), nullable=False, comment='토큰 레코드 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='소유 사용자 ID'),
    sa.Column('token', sa.Text(), nullable=False, comment='Refresh Token 값'),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False, comment='만료 일시'),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='로그아웃 등으로 인한 무효화 여부'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False, comment='신청(관심) 기록 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='신청 사업장 ID (businesses.id)'),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='대상 정책 ID (policies.id)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='신청 단계 (관심·제출·승인 등)'),
    sa.Column('applied_at', sa.TIMESTAMP(), nullable=True, comment='실제 신청(제출) 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='상태 마지막 변경 일시'),
    sa.Column('memo', sa.Text(), nullable=True, comment='사용자 메모'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_financial_snapshots',
    sa.Column('id', sa.UUID(), nullable=False, comment='재무 스냅샷 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='대상 사업장 ID (businesses.id)'),
    sa.Column('snapshot_year', sa.Integer(), nullable=False, comment='재무제표 기준 연도'),
    sa.Column('snapshot_period', sa.String(length=10), nullable=False, comment='기준 시기 (1Q, 2Q 등)'),
    sa.Column('term_type', sa.String(length=10), nullable=False, comment='공시 주기 (연간·분기 등)'),
    sa.Column('annual_revenue', sa.BigInteger(), nullable=True, comment='연매출액 (원)'),
    sa.Column('operating_profit', sa.BigInteger(), nullable=True, comment='영업이익 (원, 음수 가능) — API 명세서 #4·#5 대응'),
    sa.Column('net_income', sa.BigInteger(), nullable=True, comment='당기순이익 (원, 음수 가능)'),
    sa.Column('total_debt', sa.BigInteger(), nullable=True, comment='총 부채액 (원)'),
    sa.Column('capital', sa.BigInteger(), nullable=True, comment='자본금 (원) — API 명세서 #4·#5 대응'),
    sa.Column('debt_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='부채 비율 (%) — 자동 계산'),
    sa.Column('employee_count', sa.Integer(), nullable=True, comment='직원 수'),
    sa.Column('tax_arrears_yn', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='세금 체납 여부'),
    sa.Column('ai_analysis_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='비즈몽 재무 진단 결과 (JSON)'),
    sa.Column('ocr_status', sa.String(length=20), nullable=False, comment='OCR·분석 진행 상태 (대기·완료 등)'),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='공식 서류 기반 검증 여부'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='[Soft Delete] 활성 여부 — False 이면 삭제 처리된 레코드'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='스냅샷 생성 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'snapshot_year', name='uq_biz_financial_snapshot_year')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.UUID(), nullable=False, comment='대화방(상담 세션) 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='상담을 시작한 사용자 ID (users.id)'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='상담 시 선택된 사업장 ID (데이터 격리 및 맞춤형 상담용)'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='대화방 제목 (AI 요약 등)'),
    sa.Column('user_feedback', sa.Boolean(), nullable=True, comment='사용자 만족도 (좋아요·싫어요 등)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상담 진행 상태 (active/closed 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='대화방 생성 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='서류 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='소속 사업장 ID (businesses.id)'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='서류 종류 (사업자등록증 등)'),
    sa.Column('file_url', sa.Text(), nullable=False, comment='저장소(S3 등) 파일 경로'),
    sa.Column('ocr_status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False, comment='OCR 분석 진행 상태 (PENDING | COMPLETED | FAILED)'),
    sa.Column('ocr_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='OCR 추출 원본 데이터 (JSON). 비동기 분석 완료 시 update_document_status()로 채워진다. API 명세서 #11 ocr_data 필드에 대응.'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='[Soft Delete] 활성 여부 — False 이면 삭제 처리된 레코드'),
    sa.Column('issued_at', sa.Date(), nullable=True, comment='서류 발급 일자'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='업로드 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_requests',
    sa.Column('id', sa.UUID(), nullable=False, comment='리드 요청 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='신청 사용자 ID (users.id)'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='상담 대상 사업장 ID (businesses.id)'),
    sa.Column('lead_type', sa.String(length=50), nullable=False, comment='상담 종류 (로봇·세무 등)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='처리 상태 (신청·검토·연결완료 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='신청 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='매칭 결과 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='매칭 대상 사업장 ID (businesses.id)'),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='매칭 대상 정책 ID (policies.id)'),
    sa.Column('match_score', sa.Integer(), nullable=False, comment='매칭 점수 (0~100)'),
    sa.Column('match_status', sa.String(length=10), nullable=False, comment='신호등 상태 (G/Y/R 등)'),
    sa.Column('reason_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='점수 산정 근거 (JSON)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='매칭 판정 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='알림 고유 식별자 (자동 생성되는 우편물 번호입니다)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='수신 사용자 ID (누구에게 보낼지 정하는 수신인 주소입니다)'),
    sa.Column('business_id', sa.UUID(), nullable=True, comment='연관 사업장 ID (특정 가게와 관련된 알림일 경우에만 기록합니다)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='알림 유형 (예: POLICY_MATCH, CHAT_ANSWER 등 유형별 아이콘 구분에 사용)'),
    sa.Column('title', sa.String(length=255), server_default=sa.text("'새로운 알림'"), nullable=False, comment='알림 제목 (사용자에게 노출될 큰 글씨의 요약 내용입니다)'),
    sa.Column('message', sa.Text(), nullable=False, comment='알림 본문 (상세한 안내 문구가 담기는 그릇입니다)'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='읽음 여부 (사용자가 확인했는지 체크하는 확인 도장입니다)'),
    sa.Column('link_url', sa.Text(), nullable=True, comment='이동 URL (클릭 시 앱/웹 내 특정 페이지로 안내하는 지름길입니다)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='알림 생성 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False, comment='북마크 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='북마크 주인 (어느 사업장인가?)'),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='북마크 대상 (어떤 정책인가?)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='북마크 클릭 시점'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'policy_id', name='uq_policy_bookmark_biz_policy')
    )
    op.create_index('ix_policy_bookmark_business_id', 'policy_bookmarks', ['business_id'], unique=False)
    op.create_table('simulation_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='시뮬레이션 로그 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='기준 사업장 ID (businesses.id)'),
    sa.Column('sim_type', sa.String(length=50), nullable=False, comment='시뮬레이션 종류 (예: ADD_POINT, ROI_PREDICT)'),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='사용자 입력 조건 (JSON)'),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='계산·예측 결과 (JSON)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='실행 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='대화 메시지 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='대화 사용자 ID (users.id)'),
    sa.Column('ref_policy_id', sa.UUID(), nullable=True, comment='참조한 정책 ID (없으면 일반 상담)'),
    sa.Column('room_id', sa.UUID(), nullable=False, comment='소속 대화방 ID (chat_rooms.id)'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='화자 (user / assistant / system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='메시지 본문'),
    sa.Column('context_type', sa.String(length=20), nullable=True, comment='발생 위치 (widget / page / direct)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='메시지 생성 일시'),
    sa.Column('trace_id', sa.String(length=100), nullable=True, comment='LangSmith 등 LLM 모니터링 추적 ID'),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=8), nullable=True, comment='API 토큰 비용 (USD)'),
    sa.Column('referenced_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='RAG 참조 청크 데이터 (JSON)'),
    sa.Column('is_disliked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='사용자 비추천(싫어요) 여부'),
    sa.Column('feedback_code', sa.String(length=20), nullable=True, comment='피드백 사유 코드 (INACCURATE / UNFRIENDLY 등)'),
    sa.Column('feedback_text', sa.Text(), nullable=True, comment='피드백 상세 텍스트'),
    sa.ForeignKeyConstraint(['ref_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_logs')
    op.drop_table('simulation_logs')
    op.drop_index('ix_policy_bookmark_business_id', table_name='policy_bookmarks')
    op.drop_table('policy_bookmarks')
    op.drop_table('notifications')
    op.drop_table('match_logs')
    op.drop_table('lead_requests')
    op.drop_table('documents')
    op.drop_table('chat_rooms')
    op.drop_table('business_financial_snapshots')
    op.drop_table('applications')
    op.drop_table('user_tokens')
    op.drop_index('ix_policy_chunks_policy_id', table_name='policy_chunks')
    op.drop_table('policy_chunks')
    op.drop_table('businesses')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_policies_title'), table_name='policies')
    op.drop_index(op.f('ix_policies_region'), table_name='policies')
    op.drop_index(op.f('ix_policies_content_hash'), table_name='policies')
    op.drop_index(op.f('ix_policies_closed_at'), table_name='policies')
    op.drop_index(op.f('ix_policies_category'), table_name='policies')
    op.drop_index(op.f('ix_policies_agency_name'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_biz_picks_category'), table_name='biz_picks')
    op.drop_table('biz_picks')
    op.drop_table('batch_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
