"""complete_database_schema_v1

Revision ID: da6e1e2712e6
Revises: 42c9a8c454fc
Create Date: 2026-03-30 19:28:16.312388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da6e1e2712e6'
down_revision: Union[str, Sequence[str], None] = '42c9a8c454fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False, comment='관리자 고유 식별자'),
    sa.Column('login_id', sa.String(length=50), nullable=False, comment='관리자 로그인 ID'),
    sa.Column('password', sa.Text(), nullable=False, comment='비밀번호 해시'),
    sa.Column('role', sa.Enum('MASTER', 'OPERATOR', 'CS', name='adminrole'), nullable=False, comment='권한 등급 (MASTER·OPERATOR·CS)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='계정 활성 여부'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='계정 생성 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('batch_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='배치 실행 로그 고유 식별자'),
    sa.Column('job_name', sa.String(length=100), nullable=False, comment='작업 명칭 (예: POLICY_CRAWLING)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='실행 상태 (SUCCESS·FAILED·RUNNING 등)'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='처리 대상 전체 건수'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='성공 반영 건수'),
    sa.Column('fail_count', sa.Integer(), nullable=False, comment='실패 건수'),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='오류 상세 (JSON)'),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='작업 시작 일시'),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True, comment='작업 종료 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biz_picks',
    sa.Column('id', sa.UUID(), nullable=False, comment='콘텐츠 고유 식별자'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='콘텐츠 제목'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='카테고리 (세무·정책자금 등)'),
    sa.Column('content_md', sa.Text(), nullable=False, comment='마크다운 본문'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='작성·발행 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='감사 로그 고유 식별자'),
    sa.Column('admin_id', sa.UUID(), nullable=False, comment='작업 수행 관리자 ID (admins.id)'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='작업 유형 (POLICY_UPDATE 등)'),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='대상 엔티티 PK'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='변경 전·후 스냅샷 (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='요청 IP (IPv4/IPv6)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='작업 발생 일시'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False, comment='신청(관심) 기록 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='신청 사업장 ID (businesses.id)'),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='대상 정책 ID (policies.id)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='신청 단계 (관심·제출·승인 등)'),
    sa.Column('applied_at', sa.TIMESTAMP(), nullable=True, comment='실제 신청(제출) 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='상태 마지막 변경 일시'),
    sa.Column('memo', sa.Text(), nullable=True, comment='사용자 메모'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_financial_snapshots',
    sa.Column('id', sa.UUID(), nullable=False, comment='재무 스냅샷 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='대상 사업장 ID (businesses.id)'),
    sa.Column('snapshot_year', sa.Integer(), nullable=False, comment='재무제표 기준 연도'),
    sa.Column('snapshot_period', sa.String(length=10), nullable=False, comment='기준 시기 (1Q, 2Q 등)'),
    sa.Column('term_type', sa.String(length=10), nullable=False, comment='공시 주기 (연간·분기 등)'),
    sa.Column('annual_revenue', sa.BigInteger(), nullable=True, comment='연매출액'),
    sa.Column('net_income', sa.BigInteger(), nullable=True, comment='당기순이익'),
    sa.Column('total_debt', sa.BigInteger(), nullable=True, comment='총 부채액'),
    sa.Column('debt_ratio', sa.Numeric(precision=5, scale=2), nullable=True, comment='부채 비율 (%)'),
    sa.Column('employee_count', sa.Integer(), nullable=True, comment='직원 수'),
    sa.Column('tax_arrears_yn', sa.Boolean(), nullable=False, comment='세금 체납 여부'),
    sa.Column('ai_analysis_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='비즈몽 재무 진단 결과 (JSON)'),
    sa.Column('ocr_status', sa.String(length=20), nullable=False, comment='OCR·분석 진행 상태 (대기·완료 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='스냅샷 생성 일시'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='공식 서류 기반 검증 여부'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False, comment='서류 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='소속 사업장 ID (businesses.id)'),
    sa.Column('doc_type', sa.String(length=50), nullable=False, comment='서류 종류 (사업자등록증 등)'),
    sa.Column('file_url', sa.Text(), nullable=False, comment='저장소(S3 등) 파일 경로'),
    sa.Column('issued_at', sa.Date(), nullable=True, comment='서류 발급 일자'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='업로드 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_requests',
    sa.Column('id', sa.UUID(), nullable=False, comment='리드 요청 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='신청 사용자 ID (users.id)'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='상담 대상 사업장 ID (businesses.id)'),
    sa.Column('lead_type', sa.String(length=50), nullable=False, comment='상담 종류 (로봇·세무 등)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='처리 상태 (신청·검토·연결완료 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='신청 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='매칭 결과 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='매칭 대상 사업장 ID (businesses.id)'),
    sa.Column('policy_id', sa.UUID(), nullable=False, comment='매칭 대상 정책 ID (policies.id)'),
    sa.Column('match_score', sa.Integer(), nullable=False, comment='매칭 점수 (0~100)'),
    sa.Column('match_status', sa.String(length=10), nullable=False, comment='신호등 상태 (G/Y/R 등)'),
    sa.Column('reason_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='점수 산정 근거 (JSON)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='매칭 판정 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False, comment='알림 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='수신 사용자 ID (users.id)'),
    sa.Column('business_id', sa.UUID(), nullable=True, comment='연관 사업장 ID (businesses.id, 가게별 필터용)'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='알림 유형 (매칭·공지 등)'),
    sa.Column('message', sa.Text(), nullable=False, comment='알림 본문'),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='읽음 여부'),
    sa.Column('link_url', sa.Text(), nullable=True, comment='이동 URL'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='알림 생성 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='시뮬레이션 로그 고유 식별자'),
    sa.Column('business_id', sa.UUID(), nullable=False, comment='기준 사업장 ID (businesses.id)'),
    sa.Column('sim_type', sa.String(length=50), nullable=False, comment='시뮬레이션 종류'),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='사용자 입력 조건 (JSON)'),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='계산·예측 결과 (JSON)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='실행 일시'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='대화 메시지 고유 식별자'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='대화 사용자 ID (users.id)'),
    sa.Column('ref_policy_id', sa.UUID(), nullable=True, comment='참조한 정책 ID (policies.id, 없으면 일반 상담)'),
    sa.Column('room_id', sa.UUID(), nullable=False, comment='소속 대화방 ID (chat_rooms.id)'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='화자 (user / assistant)'),
    sa.Column('content', sa.Text(), nullable=False, comment='메시지 본문'),
    sa.Column('context_type', sa.String(length=20), nullable=True, comment='발생 위치 (위젯·페이지 등)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='메시지 생성 일시'),
    sa.Column('trace_id', sa.String(length=100), nullable=True, comment='랭스미스 등 LLM 추적 ID'),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=8), nullable=True, comment='해당 메시지 API 토큰 비용 (USD)'),
    sa.Column('referenced_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='RAG 참조 문단·청크 (JSON)'),
    sa.Column('is_disliked', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='사용자 비추천(싫어요) 여부'),
    sa.Column('feedback_code', sa.String(length=20), nullable=True, comment='피드백 사유 코드'),
    sa.Column('feedback_text', sa.Text(), nullable=True, comment='피드백 상세 텍스트'),
    sa.ForeignKeyConstraint(['ref_policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_logs')
    op.drop_table('simulation_logs')
    op.drop_table('notifications')
    op.drop_table('match_logs')
    op.drop_table('lead_requests')
    op.drop_table('documents')
    op.drop_table('business_financial_snapshots')
    op.drop_table('applications')
    op.drop_table('admin_audit_logs')
    op.drop_table('biz_picks')
    op.drop_table('batch_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
