"""Refactor domains and add policy fields

Revision ID: f273a5a15134
Revises: 1db6b0205160
Create Date: 2026-04-08 15:39:42.892641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f273a5a15134'
down_revision: Union[str, Sequence[str], None] = '1db6b0205160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False, comment='관리자 고유 식별자'),
    sa.Column('login_id', sa.String(length=50), nullable=False, comment='관리자 로그인 ID'),
    sa.Column('password', sa.Text(), nullable=False, comment='비밀번호 해시'),
    sa.Column('role', sa.Enum('MASTER', 'OPERATOR', 'CS', name='adminrole'), nullable=False, comment='권한 등급 (MASTER·OPERATOR·CS)'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='계정 활성 여부'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='계정 생성 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False, comment='감사 로그 고유 식별자'),
    sa.Column('admin_id', sa.UUID(), nullable=False, comment='작업 수행 관리자 ID (admins.id)'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='작업 유형 (POLICY_UPDATE 등)'),
    sa.Column('target_id', sa.UUID(), nullable=True, comment='대상 엔티티 PK'),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='변경 전·후 스냅샷 (JSON)'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='요청 IP (IPv4/IPv6)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='작업 발생 일시'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_audit_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
